const rawProfiles = {
  "Mexico": ["Santiago Giménez", "Forward", "前锋", "A penalty-box striker who attacks space early and finishes quickly with either foot.", "擅长提前攻击禁区空间、左右脚都能快速完成终结的中锋。"],
  "South Africa": ["Lyle Foster", "Forward", "前锋", "A mobile forward whose pace and direct running stretch defensive lines.", "移动能力出色的前锋，速度和纵向冲击能持续拉扯防线。"],
  "South Korea": ["Son Heung-min", "Forward", "前锋", "An elite transition attacker, two-footed finisher and the emotional leader of Korea.", "顶级转换进攻手，双脚终结能力突出，也是韩国队的精神领袖。"],
  "Czechia": ["Patrik Schick", "Forward", "前锋", "A tall, technically clean striker with strong aerial timing and long-range quality.", "身材高大但技术细腻，头球时机和远射能力都很突出。"],
  "Canada": ["Alphonso Davies", "Wing-back", "翼卫", "Explosive acceleration and ball carrying make him Canada's most disruptive outlet.", "爆发力和持球推进能力让他成为加拿大最具破坏力的进攻出口。"],
  "Bosnia & Herzegovina": ["Ermedin Demirović", "Forward", "前锋", "A hard-working striker who links play, presses defenders and attacks crosses.", "能串联、能逼抢、也善于冲击传中的全能型前锋。"],
  "Qatar": ["Akram Afif", "Winger", "边锋", "A creative wide forward with sharp combination play, penalties and final passes.", "配合意识敏锐，既能主罚点球，也能送出关键一传的创造型边锋。"],
  "Switzerland": ["Granit Xhaka", "Midfielder", "中场", "The tempo-setter: progressive passing, leadership and powerful shooting from distance.", "球队节拍器，兼具向前传球、领导力和强劲远射。"],
  "Brazil": ["Vinícius Júnior", "Winger", "边锋", "One-on-one acceleration, improvisation and big-game finishing make him a constant threat.", "一对一爆发、即兴创造和大赛终结能力让他始终充满威胁。"],
  "Morocco": ["Achraf Hakimi", "Right-back", "右后卫", "An ultra-fast full-back who creates overloads and turns defence into attack instantly.", "速度极快，能制造边路人数优势，并瞬间把防守转化为进攻。"],
  "Haiti": ["Duckens Nazon", "Forward", "前锋", "An experienced scorer who gives Haiti a physical reference point and direct threat.", "经验丰富的得分手，为海地提供支点和直接进攻威胁。"],
  "Scotland": ["Scott McTominay", "Midfielder", "中场", "A powerful late runner who turns midfield duels and set pieces into goals.", "后插上冲击力强，能把中场对抗和定位球转化为进球。"],
  "United States": ["Christian Pulisic", "Winger", "边锋", "A quick, intelligent attacker who carries the ball between lines and delivers in key moments.", "速度快、跑位聪明，擅长在防线之间推进并在关键时刻制造结果。"],
  "Paraguay": ["Miguel Almirón", "Attacking midfielder", "攻击中场", "Relentless running, left-footed transitions and pressing energy drive Paraguay forward.", "不知疲倦的跑动、左脚转换和高强度逼抢推动巴拉圭前进。"],
  "Australia": ["Jackson Irvine", "Midfielder", "中场", "A durable box-to-box leader with aerial presence and smart penalty-area arrivals.", "覆盖能力强的领袖型中场，兼具制空和聪明的禁区后插上。"],
  "Türkiye": ["Arda Güler", "Playmaker", "组织核心", "A left-footed creator with rare vision, close control and set-piece precision.", "左脚创造者，视野、近距离控球和定位球精度都非常罕见。"],
  "Germany": ["Jamal Musiala", "Attacking midfielder", "攻击中场", "A press-resistant dribbler who glides through tight spaces and creates numerical advantages.", "抗压盘带能力极强，能穿过狭小空间并制造局部人数优势。"],
  "Curaçao": ["Juninho Bacuna", "Midfielder", "中场", "A versatile midfielder who adds ball progression, set-piece delivery and experience.", "多面手中场，能推进、主罚定位球并提供比赛经验。"],
  "Ivory Coast": ["Simon Adingra", "Winger", "边锋", "A fearless dribbler whose direct pace can transform a balanced match in one action.", "敢于突破的直接型边锋，一次加速就可能改变均势。"],
  "Ecuador": ["Moisés Caicedo", "Midfielder", "中场", "An elite ball-winner with the range and composure to control high-intensity midfield battles.", "顶级抢断手，同时具备掌控高强度中场对抗的覆盖与冷静。"],
  "Netherlands": ["Cody Gakpo", "Forward", "前锋", "A flexible attacker who carries from the left, shoots early and attacks central spaces.", "能从左侧推进、快速起脚并攻击中路空间的多功能攻击手。"],
  "Japan": ["Takefusa Kubo", "Winger", "边锋", "A low-centre-of-gravity creator with deceptive changes of pace and precise final passes.", "重心低、变速隐蔽，最后一传精准的创造型边锋。"],
  "Sweden": ["Alexander Isak", "Forward", "前锋", "A fluid striker combining elegant close control, acceleration and calm finishing.", "兼具优雅控球、加速和冷静终结的流动型中锋。"],
  "Tunisia": ["Ellyes Skhiri", "Midfielder", "中场", "A disciplined ball-winner whose positioning protects the defence and starts transitions.", "站位纪律出色，既能保护后防，也能发起转换。"],
  "Belgium": ["Jérémy Doku", "Winger", "边锋", "An explosive dribbler built to isolate full-backs and create chaos near the box.", "爆发力极强，擅长单挑边后卫并在禁区附近制造混乱。"],
  "Egypt": ["Mohamed Salah", "Forward", "前锋", "A world-class scorer whose diagonal runs, left foot and decision-making define Egypt's attack.", "世界级得分手，斜向跑动、左脚和决策能力定义了埃及进攻。"],
  "Iran": ["Mehdi Taremi", "Forward", "前锋", "A clever penalty-area operator with strong link play and a talent for winning decisive duels.", "禁区嗅觉敏锐，串联出色，也善于赢下决定性的对抗。"],
  "New Zealand": ["Chris Wood", "Forward", "前锋", "A dominant aerial striker and experienced finisher who gives every attack a clear target.", "制空能力强、经验丰富，为每次进攻提供明确目标。"],
  "Spain": ["Lamine Yamal", "Winger", "边锋", "An extraordinary young creator with elite one-on-one skill, vision and left-footed delivery.", "非凡的年轻创造者，一对一、视野和左脚传射都达到顶级。"],
  "Cape Verde": ["Ryan Mendes", "Forward", "前锋", "An experienced wide attacker who brings calm decisions and sharp movement in transition.", "经验丰富的边路攻击手，在转换中决策冷静、跑位敏锐。"],
  "Saudi Arabia": ["Salem Al-Dawsari", "Winger", "边锋", "A fearless big-game winger with close control, curling finishes and leadership.", "敢于在大赛承担责任，近距离控球、弧线球终结和领导力兼备。"],
  "Uruguay": ["Federico Valverde", "Midfielder", "中场", "A relentless two-way midfielder with huge running power and a devastating long shot.", "攻守双向覆盖惊人，跑动能力和重炮远射都极具威力。"],
  "France": ["Kylian Mbappé", "Forward", "前锋", "Devastating acceleration, elite movement and ruthless finishing make him football's premier transition threat.", "毁灭性的加速、顶级跑位和冷酷终结，让他成为足坛最危险的转换威胁。"],
  "Senegal": ["Sadio Mané", "Forward", "前锋", "A direct, experienced attacker whose movement and competitive edge lift the entire side.", "直接而经验丰富，跑位与竞争气质能提升整支球队。"],
  "Iraq": ["Ali Jasim", "Winger", "边锋", "A bold young winger who attacks defenders, combines quickly and plays without fear.", "敢于挑战防守者、配合迅速且无所畏惧的年轻边锋。"],
  "Norway": ["Erling Haaland", "Forward", "前锋", "An unmatched penalty-box runner with extraordinary power, speed and one-touch finishing.", "无与伦比的禁区跑位，力量、速度和一脚终结都极其出色。"],
  "Argentina": ["Lionel Messi", "Playmaker", "组织核心", "A generational creator whose vision, left foot and control of match tempo remain unique.", "时代级创造者，视野、左脚和比赛节奏控制依然独一无二。"],
  "Algeria": ["Riyad Mahrez", "Winger", "边锋", "A refined left-footed creator with exceptional first touch and final-third composure.", "技术精致的左脚创造者，第一脚触球和进攻三区的冷静尤其突出。"],
  "Austria": ["Marcel Sabitzer", "Midfielder", "中场", "A high-energy midfielder who presses, shoots from range and delivers dangerous dead balls.", "高能量中场，能逼抢、远射并送出有威胁的定位球。"],
  "Jordan": ["Mousa Al-Taamari", "Winger", "边锋", "A quick, inventive dribbler and Jordan's primary outlet on the counterattack.", "速度快、盘带有想象力，是约旦反击中的第一出口。"],
  "Portugal": ["Cristiano Ronaldo", "Forward", "前锋", "One of football's greatest scorers, still defined by elite movement, heading and competitive focus.", "足坛历史级射手，顶级跑位、头球和竞争专注度仍是标志。"],
  "DR Congo": ["Yoane Wissa", "Forward", "前锋", "A fast, adaptable attacker who presses aggressively and attacks gaps across the front line.", "快速且适应性强，能积极逼抢并攻击前场各处空当。"],
  "Uzbekistan": ["Eldor Shomurodov", "Forward", "前锋", "A mobile captain whose movement, aerial work and selfless running connect the attack.", "移动型队长，以跑位、空中对抗和无私跑动串联进攻。"],
  "Colombia": ["Luis Díaz", "Winger", "边锋", "An intense one-on-one winger whose acceleration and pressing create chances from nothing.", "极具强度的一对一边锋，加速和逼抢能凭空创造机会。"],
  "England": ["Jude Bellingham", "Midfielder", "中场", "A complete midfielder with power, timing, creativity and the personality to decide major games.", "力量、时机、创造力和大赛担当兼备的全能中场。"],
  "Croatia": ["Joško Gvardiol", "Defender", "后卫", "A modern defender combining recovery speed, progressive carrying and calm distribution.", "现代型后卫，兼具回追速度、向前带球和冷静出球。"],
  "Ghana": ["Mohammed Kudus", "Attacking midfielder", "攻击中场", "A powerful, unpredictable ball carrier who breaks pressure and shoots with either foot.", "力量强、难以预测，能持球破压并用双脚完成射门。"],
  "Panama": ["Adalberto Carrasquilla", "Midfielder", "中场", "A press-resistant organiser who gives Panama rhythm, progressive passing and personality.", "抗压的组织者，为巴拿马提供节奏、向前传球和比赛气质。"]
};

export const playerProfiles = Object.fromEntries(
  Object.entries(rawProfiles).map(([team, [name, positionEn, positionZh, bioEn, bioZh]]) => [
    team,
    { name, positionEn, positionZh, bioEn, bioZh }
  ])
);
